spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/#catdogshelter
    username: #root
    password: #pwd
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none   # ???? ?? ??? none
    show-sql: true
    properties:
      hibernate.format_sql: true

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package: com.example.project.domain