# 공통 설정 + 템플릿

server:
  port: 8080
  tomcat:
    max-connections: 200

spring:
  application:
    name: CatDogShelter
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true

  # dev: application-dev.yml
  # prod: application-prod.yml
  # test: application-test.yml
  # active: {...} -> application-{...}.yml 파일 우선 적용
  profiles:
    active: dev
    
  # DB 설정
  # url, username, password은 다른 yml에서 작성
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/CatDogShelter
    username: root
    password: mariadb

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

# fatal -> error -> warn -> info -> debug -> trace
logging:
  level:
    root: INFO

filepath: # 윈도우: C:\\uploadFiles
          # max: /User/??/uploadFiles