# ?? ?? + ???
# ??? ??? ??? ?? yml ??? ??? gitignore ???? github ?? X

server:
  port: 8080
  tomcat:
    max-connections: 200

spring:
  application:
    name: CatDogShelter
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
  # ?? ?? ??? ????? ??
  # dev: application-dev.yml
  # prod: application-prod.yml
  # test: application-test.yml
  # active? ??? ??? ???? ?
  profiles:
    active: dev
  # ??? ??? ?? -
  # ?? yml???? url, username, password? ???? ?? ?? ??
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/catdogshelter
    username: #user
    password: #pwd


# fatal -> error -> warn -> info -> debug -> trace
logging:
  level:
    root: INFO

filepath: # ???: C:\\uploadFiles
          # max: /User/??/uploadFiles