# 공통 설정 + 템플릿

server:
  port: 0
  tomcat:
    max-connections: 200

spring:
  application:
    name: CatDogShelter-post-service
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true

  # dev: application-dev.yml
  # prod: application-prod.yml
  # test: application-test.yml
  # active: {...} -> application-{...}.yml 파일 우선 적용
  profiles:
    active: dev

  # DB 설정
  # url, username, password은 다른 yml에서 작성
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/catdogshelter
    username: root
    password: mariadb

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

# fatal -> error -> warn -> info -> debug -> trace
logging:
  level:
    root: debug

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

file:
  upload-dir: /Users/haeone/Desktop/be19-2nd-backoven-petShelter/uploads

# 로그인
token:
  expiration_time: 43200000
  secret: "VKKCjFzrzJQE8oM69GmgavfauYLnHnQeG4k1ab/lrYtrEQMk7o0/3j8KmqM33prEOWs5IdSVhQsbKiV3UzFhHQ=="


eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

